config/routes.rb
HwApp::Application.routes.draw do
  
  resources :apps

  root :to => 'apps#index'

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :name, :creator, :models_attributes, :controllers_attributes

  has_many :controllers
  has_many :models
  has_one  :creator

  accepts_nested_attributes_for :creator, :models, :controllers
end

app/models/controller.rb
class Controller < ActiveRecord::Base
  attr_accessible :name, :app_id

  belongs_to :app
end

app/models/creator.rb
class Creator < ActiveRecord::Base
  attr_accessible :name, :app_id

  belongs_to :app
end

app/models/model.rb
class Model < ActiveRecord::Base
  attr_accessible :name, :app_id

  belongs_to :app
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
    @creators = Creator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])
    @creator = @app.build_creator

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new
    @app.build_creator
    
    1.times { @app.controllers.build }
    1.times { @app.models.build }
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  

<div class="field">
  Creator: <br />
  <%= f.fields_for :creator do |c| %>
    <%= c.label :name %>
    <%= c.text_field :name %>
  <% end %>
  </div>

  <div class="field">
  Models: <br />
  <%= f.fields_for :models do |m| %>
    <%= m.label :name %>
    <%= m.text_field :name %>
  <% end %> 

  </div>


  <div class="field">
    Controller: <br />
    <%= f.fields_for :controllers do |co| %>
      <%= co.label :name %>
      <%= co.text_field :name %>
    <% end %> 
  </div>

 <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= app.creator %></td>
    <td><%= app.models.name %></td>
    <td><%= app.controllers.name %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Creator:</b>
  <%= @app.creator %>
</p>

<p>
  <b>Models:</b>
  <%= @app.controllers.name %>
</p>

<p>
  <b>Controllers:</b>
  <%= @app.models.name %>
</p>
<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>